# Generated by Django 5.1.dev20240514192804 on 2024-05-14 19:46

from django.db import IntegrityError, migrations, transaction


def add_posts(apps, schema_editor):
    Post = apps.get_model("blog.Post")
    User = apps.get_model("auth.User")

    Post.objects.create(title="Initial post", body="Hello world, this is the initial blog post.")
    Post.objects.create(title="Second post", body="A thoughtful second blog post, really interesting.")
    Post.objects.create(title="Third post", body="Wow, writing these posts surely is a lot of work.")

    with transaction.atomic():
        try:
            User.objects.create_user(username="test", password="test", is_staff=True, is_superuser=True)
        except IntegrityError:
            pass


def delete_all_posts(apps, schema_editor):
    Post = apps.get_model("blog.Post")
    Post.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length')
    ]

    operations = [
        migrations.RunPython(add_posts, delete_all_posts),
    ]
